### ISSUE TITLE
Will Artifika be added to this repo anytime soon?

### ISSUE THREAD

**Issue by pathumego** [cyrealtype/Cyrealfonts#1]
https://www.google.com/fonts/specimen/Artifika

**Comment by davelab6** [comment]
Alexei, could I split this out into 1 repo per font family?

**Comment by cyrealtype** [comment]
Sorry I missed this comment out. I will add this into the pipeline.

**Comment by davelab6** [comment]
Ideally you'd have 1 repo per family like https://github.com/itfoundry/ :)

**Comment by cyrealtype** [comment]
Artifika is now added to the repo. 

Dave: yes, I would appreciate if you could help me split this and make a pull request.

**Comment by davelab6** [comment]
For sorting out the splitting of the projects then we will need to do some github shenanigans... basically you need to go to create a new user account named 'alexeivanyashin' or similar, then go to  https://github.com/settings/organizations and convert your account to an organization. 

This is detailed in https://help.github.com/articles/converting-a-user-into-an-organization/

Then you can add my davelab6 account to your cyrealtype organization as a 'admin' user and I can 'do the needful' :)

**Comment by alexeiva** [comment]
Dave, I have split all the projects, and turned cyrealtype into an organisation. 

Artifika among all others have their own repos now:
https://github.com/cyrealtype/Artifika

**Comment by davelab6** [comment]
Awesome work, thank you @alexeiva :)

**Comment by davelab6** [comment]
@alexeiva is there anything unique left in this repo now?

**Comment by alexeiva** [comment]
Baumans _Cyrillic_ is unique

**Comment by davelab6** [comment]
I'm sorry I didn't get you
